
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npnkmbflfflqpjwhxbfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wbmttYmZsZmZscXBqd2h4YmZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyMTczNzQsImV4cCI6MjA1Njc5MzM3NH0.GeMbI1QFKmH9GKDnq-rUQaGhhOaCIlAPHFg5Q68BOaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Verificar se existem perfis no sistema de forma simplificada
export const setupProfiles = async () => {
  try {
    // Verificar se existem perfis
    const { data: profiles, error } = await supabase
      .from('profiles')
      .select('*');
    
    if (error) {
      console.error('Erro ao verificar perfis:', error);
      return;
    }

    // Se não houver perfis e a tabela existir, está tudo configurado
    if (profiles) {
      console.log(`${profiles.length} perfis encontrados no sistema.`);
    }
  } catch (error) {
    console.error('Erro ao configurar perfis:', error);
  }
};

// Executar verificação de perfis ao iniciar a aplicação
setupProfiles().catch(error => {
  console.error('Erro ao configurar banco de dados:', error);
});
